### ISSUE TITLE
Can't seem to search by product code

### ISSUE THREAD

**Issue by marks** [kgautreaux/pillboxr#2]

**Comment by kgautreaux** [comment]
Can you reply with the error you're getting or post a gist with the error output so I can create a reproducible test case?

**Comment by marks** [comment]
Here you go.. I am using `prodcode` as it is mentioned in the README. What's weird is that it mentions it should be a symbol though.

```
2.0.0-p247 :002 > results = Pillboxr.with(:api_key => ENV["PILLBOX_API_KEY"], :prodcode => 1659012430)
RuntimeError: Invalid attributes hash.
    from /lib/pillboxr/lib/pillboxr.rb:32:in `block in with'
    from /lib/pillboxr/lib/pillboxr.rb:25:in `each'
    from /lib/pillboxr/lib/pillboxr.rb:25:in `with'
    from (irb):2
    from /Users/mark/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'

```

**Comment by kgautreaux** [comment]
The README is just steering you wrong here.  I'm sorry about that. What you actually need to use for the hash key is `product_code`, and you need to give it a value as a string with the dash in place.  So this should work:

`results = Pillboxr.with(:api_key => ENV["PILLBOX_API_KEY"], :product_code => "0078-0176")`

I will fix the README when I get some more free time and I'll add a test case to catch this regression in the future.  I'll also probably change my API so if you use `:prodcode` as the hash key it will still do the right thing.  Hope this helps.

If I cut another gem release I'll try to update this issue pointing to the new release.

**Comment by marks** [comment]
@kgautreaux - ah! thank you.

**Comment by kgautreaux** [comment]
The README has now been fixed upstream if you want to pull.
