### ISSUE TITLE
Empty record set response from API is not XML and breaks this gem

### ISSUE THREAD

**Issue by marks** [kgautreaux/pillboxr#4]
The URL below returns "`No records found`" instead of XML. In the long run, I think this is something @lostonroute66 (David Hale @ NIH/NLM) should fix but I'll work on patching this gem to play nice with this type of response soon.

``` ruby
2.0.0-p247 :009 >   results = Pillboxr.with(:api_key => ENV["PILLBOX_API_KEY"], :color => [:blue,:green], :size => 100)
path = /PHP/pillboxAPIService.php?key=_______&color=C48333;C48329&size=100
MultiXml::ParseError: Start tag expected, '<' not found
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/multi_xml-0.5.5/lib/multi_xml/parsers/nokogiri.rb:15:in `parse'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/multi_xml-0.5.5/lib/multi_xml.rb:138:in `parse'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/parser.rb:109:in `xml'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/parser.rb:129:in `parse_supported_format'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/parser.rb:100:in `parse'
  from /Users/mark/Box Sync/Mark-Dev/ask-open-data/lib/pillboxr/lib/pillboxr/request.rb:15:in `parse'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/parser.rb:64:in `call'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/request.rb:294:in `parse_response'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/request.rb:264:in `block in handle_response'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/response.rb:23:in `call'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/response.rb:23:in `parsed_response'
  from /Users/mark/.rvm/gems/ruby-2.0.0-p247/gems/httparty-0.12.0/lib/httparty/response.rb:61:in `method_missing'
  from /Users/mark/Box Sync/Mark-Dev/ask-open-data/lib/pillboxr/lib/pillboxr/result.rb:11:in `initialize'
  from /Users/mark/Box Sync/Mark-Dev/ask-open-data/lib/pillboxr/lib/pillboxr.rb:57:in `new'
  from /Users/mark/Box Sync/Mark-Dev/ask-open-data/lib/pillboxr/lib/pillboxr.rb:57:in `complete'
  from /Users/mark/Box Sync/Mark-Dev/ask-open-data/lib/pillboxr/lib/pillboxr.rb:37:in `with'
  from (irb):9
  from /Users/mark/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'2.0.0-p247 :010 > 
```

**Comment by kgautreaux** [comment]
@marks,

Since you're showing Pillboxr more love than it has seen in a while I went ahead and added you as a collaborator to the repo.  Feel free to push that change if you want and we can work on adding tests for it.

**Comment by kgautreaux** [comment]
@marks Can you pull 81b8664 and make sure that it doesn't break anything for you and still fixes this issue?  I now have a test for rescuing the `MultiXml::ParseError` but in order to be able to test it I had to introduce a new config object and eliminate top-level constants.  I want to make sure this doesn't break anything else for you before I close this issue.  Thanks.

**Comment by marks** [comment]
@kgautreaux - yup, works for me! thanks

**Comment by ghost** [comment]
Sorry to take so long to get to this.  Will this work?

<?xml version="1.0" encoding="UTF-8" ?>
<Pills>
<disclaimer>Most images available via Pillbox are not yet part of the official drug labeling and have not yet been verified by the manufacturer/labeler. Data may be different from that submitted by the labeler. NLM makes no warranty that the data is error free. See http://pillbox.nlm.nih.gov/API-documentation.html for further information.</disclaimer>
<record_count>0</record_count>
</Pills>

**Comment by marks** [comment]
@lostonroute66 no prob! I would personally suggest the following:

```
<?xml version="1.0" encoding="UTF-8" ?>
<Pills>
<disclaimer>THE USUAL GOES HERE</disclaimer>
<record_count>0</record_count>
</Pills>
```

**Comment by ghost** [comment]
The code I pasted was reformatted.  What you pated is what I've changed the output to for empty record set returns.

Big Pillbox updates next week.  This will go in with them.
